TTK.config['ttke'] = {
    season: '1516',
	players: [
        {id: 'pam', name: 'Amland', table: 'ars|che|liv|mun|tot|mci|eve|sou|new|whu|swa|stk|wba|avl|sun|cry|lei|wat|nor|bou'.split('|')},
        {id: 'abo', name: 'Børresen', table: 'che|mci|ars|liv|mun|tot|eve|sou|stk|whu|swa|avl|cry|new|wba|sun|lei|wat|bou|nor'.split('|')},
        {id: 'fei', name: 'Einerkjær', table: 'che|ars|mun|mci|liv|tot|whu|eve|sou|stk|new|cry|swa|avl|sun|wba|wat|lei|nor|bou'.split('|')},
        {id: 'oel', name: 'Ellingsen', table: 'che|ars|mci|mun|liv|tot|stk|eve|whu|cry|new|sou|swa|sun|wba|lei|wat|avl|bou|nor'.split('|')},
        {id: 'jha', name: 'Harsem', table: 'che|ars|mci|mun|tot|liv|sou|eve|swa|wba|cry|new|stk|lei|whu|avl|sun|bou|nor|wat'.split('|')},
        {id: 'fhe', name: 'Hesselberg', table: 'mun|che|ars|mci|liv|tot|sou|eve|stk|swa|cry|whu|wba|new|avl|nor|lei|sun|wat|bou'.split('|')},
        {id: 'kla', name: 'Laskemoen', table: 'che|ars|mun|mci|liv|tot|stk|eve|whu|sou|cry|new|swa|wat|wba|bou|avl|sun|lei|nor'.split('|')},
        {id: 'ema', name: 'Martinsen', table: 'che|ars|mci|mun|liv|tot|eve|stk|sou|whu|cry|new|swa|wba|avl|wat|sun|lei|nor|bou'.split('|')},
        {id: 'mro', name: 'Røsjø', table: 'mun|che|ars|mci|tot|liv|eve|stk|sou|whu|new|cry|avl|swa|wba|lei|sun|bou|nor|wat'.split('|')},
        {id: 'ask', name: 'Skogvang', table: 'che|mun|ars|mci|eve|liv|tot|stk|new|sou|cry|whu|swa|avl|lei|wba|bou|sun|wat|nor'.split('|')},
        {id: 'lwa', name: 'Wabakken', table: 'ars|che|mci|mun|liv|tot|eve|sou|stk|whu|swa|cry|new|wba|avl|sun|lei|wat|bou|nor'.split('|')},
        {id: 'kwi', name: 'Wilsgård', table: 'che|mci|mun|ars|liv|tot|sou|eve|avl|swa|whu|stk|new|sun|wba|cry|nor|lei|bou|wat'.split('|')},
        {id: 'jov', name: 'Øverland', table: 'che|mci|ars|mun|liv|tot|sou|eve|swa|stk|cry|whu|new|sun|wba|wat|avl|lei|bou|nor'.split('|')}
	],
	teams: [
		{id: 'ars', name: 'Arsenal', fullName: 'Arsenal FC' },
		{id: 'avl', name: 'Aston Villa', fullName: 'Aston Villa FC'},
		{id: 'bou', name: 'Bournemouth', fullName: 'AFC Bournemouth'},
		{id: 'che', name: 'Chelsea', fullName: 'Chelsea FC'},
		{id: 'cry', name: 'Crystal Palace', fullName: 'Crystal Palace FC'},
		{id: 'eve', name: 'Everton', fullName: 'Everton FC'},
		{id: 'lei', name: 'Leicester', fullName: 'Leicester City FC'},
		{id: 'liv', name: 'Liverpool', fullName: 'Liverpool FC'},
		{id: 'mci', name: 'Manchester City', fullName: 'Manchester City FC'},
		{id: 'mun', name: 'Manchester United', fullName: 'Manchester United FC'},
		{id: 'new', name: 'Newcastle', fullName: 'Newcastle United FC'},
		{id: 'nor', name: 'Norwich', fullName: 'Norwich City FC'},
		{id: 'sou', name: 'Southampton', fullName: 'Southampton FC'},
		{id: 'stk', name: 'Stoke', fullName: 'Stoke City FC'},
		{id: 'sun', name: 'Sunderland', fullName: 'Sunderland AFC'},
		{id: 'swa', name: 'Swansea', fullName: 'Swansea City FC'},
		{id: 'tot', name: 'Tottenham', fullName: 'Tottenham Hotspur FC'},
        {id: 'wat', name: 'Watford', fullName: 'Watford FC'},
		{id: 'wba', name: 'West Bromwich', fullName: 'West Bromwich Albion FC'},
		{id: 'whu', name: 'West Ham', fullName: 'West Ham United FC'}
	],
	scoreArray: [-1, 1, 2, 3, 5, 7, 9, 12, 15, 18, 22, 26, 30, 35, 40, 45, 51, 57, 63, 69],
	teamColors: ['#00a623', '#8cc000', '#bc9b00', '#bc5800', '#A70700', '#ee0000', '#ee0000'],
	intervalSize: 3,
	placeColor: [
        '#00a623',
        '#4DC000',
        '#8cc000',
        '#2E0000',
        '#450000',
        '#5C0000',
        '#730000',
        '#8B0000',
        '#A20000',
        '#B90000',
        '#D00000',
        '#E70000',
        '#FF0000'
    ],
    placeFontSize: [],
    teamIdTeamNameMap: {},
    teamFullNameTeamMap: {}
};
