import { PAM, ABO, FEI, OEL, LPA, JHA, FHE, KLA, EMA, LWA, KWI, JOV } from './users';

import {
    ARS,
    BOU,
    BHA,
    BRN,
    CHE,
    CRY,
    EVE,
    HUD,
    LEI,
    LIV,
    MCI,
    MUN,
    NEW,
    SOU,
    STK,
    SWA,
    TOT,
    WAT,
    WBA,
    WHU,
} from './teams';
import { TEAM_COLORS, USER_COLORS } from './colors';

export default {
    name: 'TTKE',
    season: '1718',
    bets: [
        {
            user: PAM,
            table: [
                MCI,
                MUN,
                CHE,
                LIV,
                TOT,
                ARS,
                EVE,
                SOU,
                LEI,
                WHU,
                NEW,
                WBA,
                STK,
                CRY,
                BOU,
                BRN,
                HUD,
                WAT,
                SWA,
                BHA,
            ],
        },
        {
            user: ABO,
            table: [
                MCI,
                LIV,
                MUN,
                CHE,
                TOT,
                ARS,
                EVE,
                WHU,
                SOU,
                LEI,
                CRY,
                STK,
                NEW,
                BOU,
                WBA,
                WAT,
                HUD,
                BRN,
                SWA,
                BHA,
            ],
        },
        {
            user: FEI,
            table: [
                MUN,
                MCI,
                CHE,
                TOT,
                ARS,
                LIV,
                EVE,
                SOU,
                CRY,
                WHU,
                LEI,
                STK,
                WBA,
                NEW,
                BOU,
                BRN,
                WAT,
                BHA,
                HUD,
                SWA,
            ],
        },
        {
            user: OEL,
            table: [
                MCI,
                MUN,
                LIV,
                TOT,
                CHE,
                ARS,
                EVE,
                BOU,
                WHU,
                SOU,
                LEI,
                CRY,
                WBA,
                STK,
                NEW,
                BRN,
                BHA,
                WAT,
                SWA,
                HUD,
            ],
        },
        {
            user: LPA,
            table: [
                MCI,
                MUN,
                CHE,
                TOT,
                LIV,
                ARS,
                EVE,
                WHU,
                SOU,
                LEI,
                STK,
                CRY,
                WBA,
                NEW,
                BOU,
                WAT,
                BRN,
                SWA,
                BHA,
                HUD,
            ],
        },
        {
            user: JHA,
            table: [
                TOT,
                MCI,
                CHE,
                LIV,
                MUN,
                ARS,
                EVE,
                LEI,
                SOU,
                WHU,
                BOU,
                WBA,
                CRY,
                STK,
                NEW,
                SWA,
                BHA,
                BRN,
                WAT,
                HUD,
            ],
        },
        {
            user: FHE,
            table: [
                MCI,
                TOT,
                MUN,
                LIV,
                CHE,
                ARS,
                SOU,
                EVE,
                WHU,
                CRY,
                WBA,
                STK,
                BOU,
                BRN,
                LEI,
                WAT,
                SWA,
                HUD,
                BHA,
                NEW,
            ],
        },
        {
            user: KLA,
            table: [
                MCI,
                CHE,
                MUN,
                LIV,
                ARS,
                TOT,
                EVE,
                LEI,
                SOU,
                WHU,
                BOU,
                WBA,
                BHA,
                CRY,
                WAT,
                NEW,
                STK,
                SWA,
                HUD,
                BRN,
            ],
        },
        {
            user: EMA,
            table: [
                MCI,
                MUN,
                TOT,
                CHE,
                LIV,
                ARS,
                EVE,
                WHU,
                SOU,
                LEI,
                BOU,
                WBA,
                NEW,
                STK,
                CRY,
                BRN,
                BHA,
                WAT,
                SWA,
                HUD,
            ],
        },
        {
            user: LWA,
            table: [
                MCI,
                CHE,
                MUN,
                ARS,
                TOT,
                LIV,
                EVE,
                SOU,
                BOU,
                WHU,
                WBA,
                STK,
                LEI,
                NEW,
                CRY,
                BRN,
                WAT,
                SWA,
                BHA,
                HUD,
            ],
        },
        {
            user: KWI,
            table: [
                MCI,
                CHE,
                MUN,
                ARS,
                TOT,
                LIV,
                EVE,
                WHU,
                SOU,
                LEI,
                STK,
                NEW,
                BOU,
                WBA,
                WAT,
                BRN,
                SWA,
                CRY,
                BHA,
                HUD,
            ],
        },
        {
            user: JOV,
            table: [
                MCI,
                CHE,
                TOT,
                ARS,
                LIV,
                MUN,
                EVE,
                LEI,
                BOU,
                SOU,
                WHU,
                CRY,
                WBA,
                STK,
                NEW,
                SWA,
                BRN,
                WAT,
                BHA,
                HUD,
            ],
        },
    ],
    user: {
        colors: [
            USER_COLORS.WINNER_FIRST,
            USER_COLORS.WINNER_SECOND,
            USER_COLORS.WINNER_THIRD,
            USER_COLORS.LOSER_FIRST,
            USER_COLORS.LOSER_ALT6,
            USER_COLORS.LOSER_ALT8,
            USER_COLORS.LOSER_ALT10,
            USER_COLORS.LOSER_ALT12,
            USER_COLORS.LOSER_ALT14,
            USER_COLORS.LOSER_ALT16,
            USER_COLORS.LOSER_ALT18,
            USER_COLORS.LOSER_LAST,
        ],
    },
    team: {
        colors: Object.values(TEAM_COLORS),
        interval: 3,
    },
};
