import api from '../api/football-data-org-1819';
import adapter from '../adapters/football-data-org-1819';
import { PAM, FEI, OEL, JHA, KLA, EMA, LWA, JOV, SOR } from './users';
import {
    ARS,
    BOU,
    BHA,
    BRN,
    CAR,
    CHE,
    CRY,
    EVE,
    FUL,
    HUD,
    LEI,
    LIV,
    MCI,
    MUN,
    NEW,
    SOU,
    TOT,
    WAT,
    WHU,
    WOL,
} from './teams';
import { TEAM_COLORS, USER_COLORS } from './colors';

// Name
const name = 'TTKE';

// Season
const season = '1819';

// Users
const users = [PAM, FEI, OEL, JHA, KLA, EMA, LWA, JOV, SOR];

// User colors
const userColors = {
    1: USER_COLORS.WINNER_FIRST,
    2: USER_COLORS.WINNER_SECOND,
    3: USER_COLORS.WINNER_THIRD,
    4: USER_COLORS.LOSER_FIRST,
    5: USER_COLORS.LOSER_ALT6,
    6: USER_COLORS.LOSER_ALT10,
    7: USER_COLORS.LOSER_ALT14,
    8: USER_COLORS.LOSER_ALT17,
    9: USER_COLORS.LOSER_LAST,
};

// Teams
const teams = [
    ARS,
    BOU,
    BHA,
    BRN,
    CAR,
    CHE,
    CRY,
    EVE,
    FUL,
    HUD,
    LEI,
    LIV,
    MCI,
    MUN,
    NEW,
    SOU,
    TOT,
    WAT,
    WHU,
    WOL,
];

// Team legend
const teamLegend = {
    0: { points: -1, color: TEAM_COLORS.CORRECT },
    1: { points: 1, color: TEAM_COLORS.GOOD },
    2: { points: 2, color: TEAM_COLORS.GOOD },
    3: { points: 3, color: TEAM_COLORS.GOOD },
    4: { points: 5, color: TEAM_COLORS.MEDIUM },
    5: { points: 7, color: TEAM_COLORS.MEDIUM },
    6: { points: 9, color: TEAM_COLORS.MEDIUM },
    7: { points: 12, color: TEAM_COLORS.BAD },
    8: { points: 15, color: TEAM_COLORS.BAD },
    9: { points: 18, color: TEAM_COLORS.BAD },
    10: { points: 22, color: TEAM_COLORS.HORRIBLE },
    11: { points: 26, color: TEAM_COLORS.HORRIBLE },
    12: { points: 30, color: TEAM_COLORS.HORRIBLE },
    13: { points: 35, color: TEAM_COLORS.HORRIBLE },
    14: { points: 40, color: TEAM_COLORS.HORRIBLE },
    15: { points: 45, color: TEAM_COLORS.HORRIBLE },
    16: { points: 51, color: TEAM_COLORS.HORRIBLE },
    17: { points: 57, color: TEAM_COLORS.HORRIBLE },
    18: { points: 63, color: TEAM_COLORS.HORRIBLE },
    19: { points: 70, color: TEAM_COLORS.HORRIBLE },
};

// Bets
const bets = [
    {
        user: PAM,
        table: [
            LIV,
            MCI,
            CHE,
            ARS,
            TOT,
            MUN,
            EVE,
            WHU,
            WOL,
            LEI,
            BRN,
            SOU,
            CRY,
            BOU,
            FUL,
            NEW,
            BHA,
            WAT,
            HUD,
            CAR,
        ],
    },
    {
        user: FEI,
        table: [
            MCI,
            MUN,
            CHE,
            LIV,
            TOT,
            ARS,
            EVE,
            LEI,
            SOU,
            WHU,
            CRY,
            NEW,
            BRN,
            BOU,
            WOL,
            WAT,
            FUL,
            BHA,
            HUD,
            CAR,
        ],
    },
    {
        user: OEL,
        table: [
            MCI,
            LIV,
            TOT,
            MUN,
            ARS,
            CHE,
            EVE,
            WHU,
            SOU,
            BRN,
            WOL,
            CRY,
            LEI,
            BOU,
            NEW,
            BHA,
            FUL,
            WAT,
            HUD,
            CAR,
        ],
    },
    {
        user: JHA,
        table: [
            MCI,
            TOT,
            LIV,
            MUN,
            ARS,
            CHE,
            EVE,
            WHU,
            SOU,
            LEI,
            CRY,
            WOL,
            WAT,
            BOU,
            NEW,
            BHA,
            BRN,
            FUL,
            HUD,
            CAR,
        ],
    },
    {
        user: KLA,
        table: [
            MCI,
            LIV,
            MUN,
            TOT,
            ARS,
            EVE,
            CHE,
            WHU,
            LEI,
            FUL,
            CRY,
            WOL,
            BOU,
            BHA,
            SOU,
            NEW,
            BRN,
            HUD,
            CAR,
            WAT,
        ],
    },
    {
        user: EMA,
        table: [
            MCI,
            LIV,
            MUN,
            TOT,
            CHE,
            ARS,
            EVE,
            WHU,
            BRN,
            WOL,
            LEI,
            CRY,
            FUL,
            SOU,
            BOU,
            NEW,
            BHA,
            CAR,
            WAT,
            HUD,
        ],
    },
    {
        user: LWA,
        table: [
            MCI,
            LIV,
            TOT,
            MUN,
            ARS,
            CHE,
            EVE,
            WHU,
            SOU,
            LEI,
            BRN,
            WOL,
            CRY,
            BOU,
            NEW,
            BHA,
            FUL,
            WAT,
            HUD,
            CAR,
        ],
    },
    {
        user: SOR,
        table: [
            LIV,
            MCI,
            TOT,
            CHE,
            MUN,
            ARS,
            EVE,
            WOL,
            WHU,
            LEI,
            SOU,
            CRY,
            NEW,
            FUL,
            BRN,
            WAT,
            BOU,
            BHA,
            HUD,
            CAR,
        ],
    },
    {
        user: JOV,
        table: [
            MCI,
            LIV,
            TOT,
            MUN,
            CHE,
            ARS,
            EVE,
            WHU,
            WOL,
            LEI,
            BRN,
            SOU,
            CRY,
            NEW,
            BOU,
            FUL,
            BHA,
            WAT,
            CAR,
            HUD,
        ],
    },
];

export default {
    api,
    adapter,
    name,
    season,
    bets,
    user: {
        users: users,
        colors: userColors,
    },
    team: {
        teams: teams,
        legend: teamLegend,
    },
};
