import api from '../api/football-data-org-2021';
import adapter from '../adapters/football-data-org-2021';
import { PAM, FEI, OEL, JHA, KLA, EMA, JOV, ABO, FHE, LPA } from './users';
import {
    ARS,
    AVL,
    BHA,
    BRN,
    CHE,
    CRY,
    EVE,
    FUL,
    LEE,
    LEI,
    LIV,
    MCI,
    MUN,
    NEW,
    SHU,
    SOU,
    TOT,
    WBA,
    WHU,
    WOL,
} from './teams';
import { TEAM_COLORS, USER_COLORS } from './colors';

// Name
const name = 'TTKE';

// Season
const season = '2021';

// Users
const users = [PAM, FEI, OEL, JHA, KLA, EMA, JOV, ABO, FHE, LPA];

// User colors
const userColors = {
    1: USER_COLORS.WINNER_FIRST,
    2: USER_COLORS.WINNER_SECOND,
    3: USER_COLORS.WINNER_THIRD,
    4: USER_COLORS.LOSER_FIRST,
    5: USER_COLORS.LOSER_ALT5,
    6: USER_COLORS.LOSER_ALT8,
    7: USER_COLORS.LOSER_ALT11,
    8: USER_COLORS.LOSER_ALT14,
    9: USER_COLORS.LOSER_ALT17,
    10: USER_COLORS.LOSER_LAST,
};

// Teams
const teams = [
    ARS,
    AVL,
    BHA,
    BRN,
    CHE,
    CRY,
    EVE,
    FUL,
    LEE,
    LEI,
    LIV,
    MCI,
    MUN,
    NEW,
    SHU,
    SOU,
    TOT,
    WBA,
    WHU,
    WOL,
];

// Team legend
const teamLegend = {
    0: { points: -1, color: TEAM_COLORS.CORRECT },
    1: { points: 1, color: TEAM_COLORS.GOOD },
    2: { points: 2, color: TEAM_COLORS.GOOD },
    3: { points: 3, color: TEAM_COLORS.GOOD },
    4: { points: 5, color: TEAM_COLORS.MEDIUM },
    5: { points: 7, color: TEAM_COLORS.MEDIUM },
    6: { points: 9, color: TEAM_COLORS.MEDIUM },
    7: { points: 12, color: TEAM_COLORS.BAD },
    8: { points: 15, color: TEAM_COLORS.BAD },
    9: { points: 18, color: TEAM_COLORS.BAD },
    10: { points: 22, color: TEAM_COLORS.HORRIBLE },
    11: { points: 26, color: TEAM_COLORS.HORRIBLE },
    12: { points: 30, color: TEAM_COLORS.HORRIBLE },
    13: { points: 35, color: TEAM_COLORS.HORRIBLE },
    14: { points: 40, color: TEAM_COLORS.HORRIBLE },
    15: { points: 45, color: TEAM_COLORS.HORRIBLE },
    16: { points: 51, color: TEAM_COLORS.HORRIBLE },
    17: { points: 57, color: TEAM_COLORS.HORRIBLE },
    18: { points: 63, color: TEAM_COLORS.HORRIBLE },
    19: { points: 70, color: TEAM_COLORS.HORRIBLE },
};

// Bets
const bets = [
    {
        user: PAM,
        table: [
            LIV,
            MCI,
            MUN,
            CHE,
            ARS,
            TOT,
            WOL,
            LEI,
            EVE,
            SOU,
            BRN,
            SHU,
            LEE,
            BHA,
            WHU,
            NEW,
            CRY,
            AVL,
            WBA,
            FUL,
        ],
    },
    {
        user: FEI,
        table: [
            MCI,
            LIV,
            CHE,
            MUN,
            ARS,
            TOT,
            LEI,
            WOL,
            EVE,
            SHU,
            CRY,
            LEE,
            WHU,
            SOU,
            NEW,
            BRN,
            BHA,
            AVL,
            FUL,
            WBA,
        ],
    },
    {
        user: OEL,
        table: [
            MCI,
            LIV,
            CHE,
            MUN,
            ARS,
            TOT,
            WOL,
            EVE,
            SOU,
            LEI,
            SHU,
            BRN,
            LEE,
            NEW,
            CRY,
            BHA,
            WHU,
            AVL,
            WBA,
            FUL,
        ],
    },
    {
        user: JHA,
        table: [
            LIV,
            MCI,
            CHE,
            TOT,
            MUN,
            ARS,
            LEI,
            WOL,
            EVE,
            SOU,
            NEW,
            BHA,
            WHU,
            SHU,
            LEE,
            BRN,
            AVL,
            CRY,
            WBA,
            FUL,
        ],
    },
    {
        user: KLA,
        table: [
            LIV,
            MCI,
            CHE,
            MUN,
            ARS,
            WOL,
            LEI,
            EVE,
            TOT,
            SOU,
            SHU,
            NEW,
            LEE,
            BRN,
            WHU,
            CRY,
            AVL,
            BHA,
            WBA,
            FUL,
        ],
    },
    {
        user: EMA,
        table: [
            LIV,
            MCI,
            MUN,
            CHE,
            ARS,
            TOT,
            WOL,
            LEI,
            EVE,
            SOU,
            BRN,
            LEE,
            SHU,
            WHU,
            NEW,
            BHA,
            AVL,
            CRY,
            WBA,
            FUL,
        ],
    },
    {
        user: JOV,
        table: [
            MCI,
            LIV,
            MUN,
            CHE,
            TOT,
            ARS,
            LEI,
            WOL,
            EVE,
            SOU,
            WHU,
            BRN,
            SHU,
            BHA,
            CRY,
            LEE,
            NEW,
            AVL,
            FUL,
            WBA,
        ],
    },
    {
        user: ABO,
        table: [
            MCI,
            LIV,
            CHE,
            ARS,
            MUN,
            TOT,
            WOL,
            LEI,
            EVE,
            WHU,
            SOU,
            BRN,
            SHU,
            LEE,
            NEW,
            BHA,
            AVL,
            CRY,
            WBA,
            FUL,
        ],
    },
    {
        user: FHE,
        table: [
            LIV,
            MCI,
            CHE,
            MUN,
            ARS,
            WOL,
            EVE,
            TOT,
            LEI,
            BRN,
            SHU,
            WHU,
            SOU,
            CRY,
            NEW,
            LEE,
            BHA,
            AVL,
            FUL,
            WBA,
        ],
    },
    {
        user: LPA,
        table: [
            LIV,
            MCI,
            CHE,
            MUN,
            TOT,
            ARS,
            EVE,
            WOL,
            LEI,
            SOU,
            LEE,
            NEW,
            WHU,
            SHU,
            AVL,
            BRN,
            BHA,
            CRY,
            WBA,
            FUL,
        ],
    },
];

export default {
    api,
    adapter,
    name,
    season,
    bets,
    user: {
        users,
        colors: userColors,
    },
    team: {
        teams: teams,
        legend: teamLegend,
    },
};
