import api from '../api/football-data-org-2122';
import adapter from '../adapters/football-data-org-2122';
import { FHE, KLA, EMA, PAM, OEL, FEI, LWA, ABO, LPA, JHA, JOV } from './users';
import {
    ARS,
    AVL,
    BHA,
    BRE,
    BRN,
    CHE,
    CRY,
    EVE,
    LEE,
    LEI,
    LIV,
    MCI,
    MUN,
    NEW,
    NOR,
    SOU,
    TOT,
    WAT,
    WHU,
    WOL,
} from './teams';
import { TEAM_COLORS, USER_COLORS } from './colors';

// Name
const name = 'TTKE';

// Season
const season = '2122';

// Users
const users = [FHE, KLA, EMA, PAM, OEL, FEI, LWA, ABO, LPA, JHA, JOV];

// User colors
const userColors = {
    1: USER_COLORS.WINNER_FIRST,
    2: USER_COLORS.WINNER_SECOND,
    3: USER_COLORS.WINNER_THIRD,
    4: USER_COLORS.LOSER_FIRST,
    5: USER_COLORS.LOSER_ALT5,
    6: USER_COLORS.LOSER_ALT7,
    7: USER_COLORS.LOSER_ALT10,
    8: USER_COLORS.LOSER_ALT13,
    9: USER_COLORS.LOSER_ALT16,
    10: USER_COLORS.LOSER_ALT19,
    11: USER_COLORS.LOSER_LAST,
};

// Teams
const teams = [
    ARS,
    AVL,
    BHA,
    BRE,
    BRN,
    CHE,
    CRY,
    EVE,
    LEE,
    LEI,
    LIV,
    MCI,
    MUN,
    NEW,
    NOR,
    SOU,
    TOT,
    WAT,
    WHU,
    WOL,
];

// Team legend
const teamLegend = {
    0: { points: -1, color: TEAM_COLORS.CORRECT },
    1: { points: 1, color: TEAM_COLORS.GOOD },
    2: { points: 2, color: TEAM_COLORS.GOOD },
    3: { points: 3, color: TEAM_COLORS.GOOD },
    4: { points: 5, color: TEAM_COLORS.MEDIUM },
    5: { points: 7, color: TEAM_COLORS.MEDIUM },
    6: { points: 9, color: TEAM_COLORS.MEDIUM },
    7: { points: 12, color: TEAM_COLORS.BAD },
    8: { points: 15, color: TEAM_COLORS.BAD },
    9: { points: 18, color: TEAM_COLORS.BAD },
    10: { points: 22, color: TEAM_COLORS.HORRIBLE },
    11: { points: 26, color: TEAM_COLORS.HORRIBLE },
    12: { points: 30, color: TEAM_COLORS.HORRIBLE },
    13: { points: 35, color: TEAM_COLORS.HORRIBLE },
    14: { points: 40, color: TEAM_COLORS.HORRIBLE },
    15: { points: 45, color: TEAM_COLORS.HORRIBLE },
    16: { points: 51, color: TEAM_COLORS.HORRIBLE },
    17: { points: 57, color: TEAM_COLORS.HORRIBLE },
    18: { points: 63, color: TEAM_COLORS.HORRIBLE },
    19: { points: 70, color: TEAM_COLORS.HORRIBLE },
};

// Bets
const bets = [
    {
        user: PAM,
        table: [
            MCI,
            LIV,
            CHE,
            MUN,
            TOT,
            LEI,
            ARS,
            WHU,
            AVL,
            LEE,
            EVE,
            WOL,
            NEW,
            CRY,
            BRN,
            BHA,
            SOU,
            BRE,
            WAT,
            NOR,
        ],
    },
    {
        user: FEI,
        table: [
            MUN,
            MCI,
            LIV,
            CHE,
            ARS,
            LEI,
            TOT,
            WHU,
            LEE,
            EVE,
            AVL,
            CRY,
            NEW,
            BHA,
            WOL,
            SOU,
            WAT,
            BRE,
            BRN,
            NOR,
        ],
    },
    {
        user: OEL,
        table: [
            MCI,
            MUN,
            LIV,
            CHE,
            ARS,
            LEI,
            TOT,
            WHU,
            LEE,
            AVL,
            EVE,
            BHA,
            WOL,
            NEW,
            CRY,
            SOU,
            BRE,
            BRN,
            NOR,
            WAT,
        ],
    },
    {
        user: JHA,
        table: [
            MCI,
            MUN,
            LIV,
            TOT,
            CHE,
            LEI,
            LEE,
            EVE,
            ARS,
            AVL,
            WHU,
            WOL,
            CRY,
            SOU,
            BHA,
            BRN,
            BRE,
            NEW,
            WAT,
            NOR,
        ],
    },
    {
        user: KLA,
        table: [
            LIV,
            MCI,
            CHE,
            MUN,
            LEI,
            TOT,
            ARS,
            EVE,
            WHU,
            LEE,
            AVL,
            BHA,
            WOL,
            SOU,
            NEW,
            BRE,
            CRY,
            WAT,
            BRN,
            NOR,
        ],
    },
    {
        user: EMA,
        table: [
            MCI,
            MUN,
            LIV,
            CHE,
            LEI,
            TOT,
            ARS,
            WHU,
            LEE,
            AVL,
            EVE,
            WOL,
            BHA,
            SOU,
            NEW,
            CRY,
            BRN,
            BRE,
            WAT,
            NOR,
        ],
    },
    {
        user: JOV,
        table: [
            MCI,
            LIV,
            CHE,
            MUN,
            LEI,
            WHU,
            TOT,
            ARS,
            LEE,
            AVL,
            EVE,
            BHA,
            WOL,
            NEW,
            SOU,
            CRY,
            BRN,
            BRE,
            NOR,
            WAT,
        ],
    },
    {
        user: ABO,
        table: [
            MCI,
            LIV,
            MUN,
            CHE,
            ARS,
            LEI,
            TOT,
            WHU,
            AVL,
            LEE,
            EVE,
            WOL,
            NEW,
            BHA,
            SOU,
            CRY,
            BRE,
            BRN,
            NOR,
            WAT,
        ],
    },
    {
        user: FHE,
        table: [
            MCI,
            CHE,
            MUN,
            LIV,
            LEI,
            WHU,
            TOT,
            EVE,
            ARS,
            LEE,
            AVL,
            CRY,
            NEW,
            BRN,
            SOU,
            WOL,
            BHA,
            NOR,
            WAT,
            BRE,
        ],
    },
    {
        user: LPA,
        table: [
            MCI,
            CHE,
            MUN,
            LIV,
            LEI,
            TOT,
            ARS,
            AVL,
            LEE,
            WHU,
            EVE,
            WOL,
            BHA,
            BRN,
            NEW,
            CRY,
            BRE,
            SOU,
            WAT,
            NOR,
        ],
    },
    {
        user: LWA,
        table: [
            MCI,
            CHE,
            LIV,
            MUN,
            LEI,
            TOT,
            ARS,
            EVE,
            LEE,
            WHU,
            AVL,
            BHA,
            WOL,
            NEW,
            SOU,
            BRE,
            BRN,
            CRY,
            NOR,
            WAT,
        ],
    },
];

export default {
    api,
    adapter,
    name,
    season,
    bets,
    user: {
        users,
        colors: userColors,
    },
    team: {
        teams: teams,
        legend: teamLegend,
    },
};
